<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{0d037d36-53d9-4a5a-a763-1819dd5d0f00}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Hannes Viljamaa
motor();
light();
//Hardware();
control();
blinker();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
